### ISSUE TITLE
Restructure data directory?

### ISSUE THREAD

**Issue by braydentang1** [UBC-MDS/DSCI_522-Group-403-Student-Performance#10]
Should we restructure the data directory to have subdirectories "raw" (the .zip file) and "processed (or better name)" (the train, test sets) perhaps?

This will require us to modify a few scripts but right now I think the data directory is a bit cluttered looking. 
If you guys don't agree, then no big deal.

**Comment by kfoofw** [comment]
I agree with this. It's a good idea to make it more segmented since we have 4 raw data files in the first place.

**Comment by brendoncampbell** [comment]
Addressed by pull request #15
