### ISSUE TITLE
Feedback Session

### ISSUE THREAD

**Issue by braydentang1** [UBC-MDS/DSCI_522-Group-403-Student-Performance#45]
- Ordinal features...treating them as continuous. 
> We have decided not to address this because while there does exist ordinal regression as a pure linear model, ML implementations of ordinal response variables are not straightforward nor consistent.
- Feature names...rename them in the plots or have a glossary in the plots because the features are difficult.
> Will probably address this with a glossary.
- The boxplot might be a bit busy, might be too much.
> Will probably not address this. We feel the boxplot provides a lot of information about our entire dataset.
- Rearrange the boxplot so that the most important features are near the top of the plot.
>  Will probably not do this since this is not trivial.

**Comment by brendoncampbell** [comment]
> Feature names...rename them in the plots or have a glossary in the plots because the features are difficult. 

Addressed in PR #50
