### ISSUE TITLE
Group feedback

### ISSUE THREAD

**Issue by brendoncampbell** [UBC-MDS/DSCI_522-Group-403-Student-Performance#47]
1. either add a table with descriptions of each of the features or rename the features so they're more interpretable on the plots (@brendoncampbell to update)
2. remove the trend line in the G3 feature density plot, the histogram communicates the distribution well enough (@braydentang1  to update)
3. when reporting the model scores, keep the same order in the tables (@kfoofw  to update)
4. get rid of the failures feature (this was already noted in our reflections & next steps section, but we've decided not to action it for this report)
5. consider looking at the feature importances from different models and compare them (again, already noted in our reflections but for simplicity sake we decided to focus on the best-performing model only)

**Comment by kfoofw** [comment]
3. when reporting the model scores, keep the same order in the tables (@kfoofw to update)

Completed in #49

**Comment by kfoofw** [comment]
2. remove the trend line in the G3 feature density plot, the histogram communicates the distribution well enough (@braydentang1 to update)

completed in #48

**Comment by brendoncampbell** [comment]
1. either add a table with descriptions of each of the features or rename the features so they're more interpretable on the plots (@brendoncampbell to update)

completed in #50
