### ISSUE TITLE
Visualizations Feedback!

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522-Group-403-Student-Performance#54]
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- - [x] Great job adding figure numbers and captions! Though your captions could have been a bit more informative, overall this is a very good practice
- - [x] Figure 1: 
	- - [x] Correlation matrix is a very effective way of seeing all of your data - excellent!
	- - [x] Consider setting diagonal values on your correlation map to be 0 or nan; those will really stand out otherwise.
	- - [x] Ideally, you only want to show half the correlation map as the other half is redundant (see example [here](http://www.sthda.com/sthda/RDoc/figure/ggplot2/ggplot2-correlation-matrix-heatmap-add-correlation-coefficients-1.png)) - let me know if you figure out how to do this in Altair
- - [x] Figure 2:
	- - [x] I don't love this plot. It's too much, can't really extract anything of value. This may be good for EDA, but probably doesn't belong in a final report
- - [x] Figure 3
	- - [x] Great use of ridgeplot! I think this nicely captures everything you want to show
	- - [x] Y-axis label should be much more informative than 'G3'
	- - [x] Minor stylistic thing which you can ignore if you like, but 'absences' looks kinda lonely in the corner there; consider centering the label
- - [x] Figure 4
	- - [x] Annotations are nice, appropriate and useful!
	- - [x] Better x and y labels
- - [x] Tables:
	- - [x] Do you need that many significant figures on your cv and and test set scores?
- - [x] Figure 5:
	- - [x] Nice, interesting use of lollipop chart 
	- - [x] Good to see features on the y-axis! Much easier to read, also great that you ordered them by rank!
	- - [x] Sig figs on importance scores
- - [x] Overall great work with your plot choices! For almost every plot I was able to understand what you were trying to convey. Please try and address the feedback above for your plots to improve your report!

**Comment by braydentang1** [comment]
Thanks Firas for the valuable feedback! Addressed in #58.
